### ISSUE TITLE
crash on Big Sur beta 8

### ISSUE THREAD

**Issue by scheblein** [ProfileCreator/ProfileCreator#223] opened 2020-09-28 15:28 UTC
Using Profile Creator 0.3.2

From Apple Crash Report:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSTableView variable rowHeight error: The value must be > 0 for row 0, but the delegate <ProfileCreator.MainWindowOutlineViewController: 0x60000164cbd0> gave 0.000.'
abort() called
terminating with uncaught exception of type NSException

**Comment by apizz** [comment] 2020-09-28 15:38
Duplicate of #217.  Please use grab the currently unreleased 0.3.3 version from the #profilecreator MacAdmins Slack channel: https://macadmins.slack.com/archives/C2N7MED7G/p1600361509043000

**Closed** 2020-09-28 15:38 UTC
Labels: duplicate
