### ISSUE TITLE
Crashes on open on macOS Big Sur

### ISSUE THREAD

**Issue by kylejericson** [ProfileCreator/ProfileCreator#227] opened 2020-11-15 07:07 UTC
Installed macOS Big Sur and this app crashes at open.

**Comment by apizz** [comment] 2020-11-15 17:28
Duplicate of #217. Please grab the currently unreleased 0.3.3 version from the #profilecreator MacAdmins Slack channel: https://macadmins.slack.com/archives/C2N7MED7G/p1600361509043000

**Closed** 2020-11-15 18:19 UTC
Labels: duplicate
