### ISSUE TITLE
802.1x not work autojoin. ethernet not connect to wired network 802.1x above login user

### ISSUE THREAD

**Issue by a-dorofeev** [ProfileCreator/ProfileCreator#206] opened 2020-02-19 10:28 UTC

**Comment by apizz** [comment] 2020-02-27 03:51
Marking as duplicate of https://github.com/ProfileCreator/ProfileManifests/issues/231.  Just submitted a PR to add these missing manifests.

**Closed by apizz** 2020-02-27 03:51 UTC
Labels: duplicate
