### ISSUE TITLE
Tabulation between input field

### ISSUE THREAD

**Issue by ygini** [ProfileCreator/ProfileCreator#18] opened 2016-06-24 18:08 UTC
When editing a profile (for example AD certs) the tab key don't allow to pass from field to field.

**Comment by erikberglund** [comment] 2016-06-26 17:26
This is something I've been thinking about and have not investigated enough. As the manifest content is a table view, tabbing doesn't behave as it usually do for a window with elements. This is what happens:

If you click on a row, you can tab within that row, but when you tab from the last item in the row the tab is returned to the row view, not the next row.

If you click on a row, or have an item that isn't editable (i.e. not a text field) you can use the arrow keys up/down to move between the rows. So it's possible to navigate, it's just not shown when the entire row is selected. And this is not the intended behavior.

So, the solution, when reading up on this, is to either subclass or register for a delegate call, but as I haven't gone into this enough I don't have a complete solution.

I tried setting next key view, but that didn't work, and doesn't seem to work between the table view as it handles the tab key in a special way.

I think this response is related: http://lists.apple.com/archives/cocoa-dev/2007/Oct/msg01702.html

Anyway, this is something I want to fix as it's an expected behavior. So I will try to see what works best, but might prioritize some more base features at the moment, but it will not be forgotten as I think about it myself each time I test the application.

**Comment by ygini** [comment] 2016-06-26 17:29
What's the need for table view here?
Does it need dynamic redraw after initial load?

**Comment by erikberglund** [comment] 2016-06-26 18:25
The table view solves a lot of problems. I have not hardcoded manifest UI, all manifest ui and export is created from the manifest plist config file. That file tells the app what payload key, type, name, description, input type (textfield, checkbox etc) and some specifics as the different payloads have different styles and requirements.

All this is to have the app be easy to update just modify the manifest plist, but also make it easy to add the automatic support when reading local setting files etc, like MCXToProfile. As well as reading and presenting any custom payload info and it's export needs.

Now I saw in macOS 10.12 there's a new type that would salve all this, but I'm quite invested in the table view now. It would be possible to just add views and skip the table view, but a table view solves so many other things automatically that I otherwise would have to code myself as keeping track of the views, interaction, reloading etc.

Yes, there is a need to dynamically reload just single rows or the entire table depeding if the user changes the profile scope for example, or selects a checkbox that another row depends on which updates that field to be required as an example.

So the TableView is the base for all of this. And was the best way I could figure out to do this dynamic UI creation, where i can just specify some base things like, i want a textfield, it's required, it sets this payload key of this type etc.

So, at least now that is not something easy to change. And, I've read of solutions to the tabbing problem, so I believe it is possible as it's often used in "spreadsheet" like applications etc.

**Comment by ygini** [comment] 2016-06-26 18:44
OK. I understand the need. So we need to find a way to handle tab in table view. 

Are you cell based or view based?

**Comment by erikberglund** [comment] 2016-10-12 11:11
Closing because of rewrite. These issues will have to be created again if they appear.

**Closed by erikberglund** 2016-10-12 11:11 UTC
