### ISSUE TITLE
Request: Ability to search for key

### ISSUE THREAD

**Issue by dannyhanes** [ProfileCreator/ProfileCreator#191] opened 2019-11-01 15:08 UTC
Just started messing with ProfileCreator and love how easy it is. 

For most profiles, there are not that many keys and finding the ones you want is pretty painless. However for something like Google Chrome I would LOVE to be able to hit cmd+f to find the key I am looking for. There are a ton of options and scrolling through the list can be a little painful. haha

Thanks for the app!

**Comment by apizz** [comment] 2019-11-01 15:38
Hi, @dannyhanes .  This is a duplicate of https://github.com/ProfileCreator/ProfileCreator/issues/97. 
 This feature was always planned, but with no devs contributing code we're kind of stuck.

If you look in the profilecreator MacAdmins channel you'll see some discussion around an iMazing Profile Creation Tool (in beta) made by DigiDNA that utilizes the same [ProfileManifests](https://github.com/ProfileCreator/ProfileManifests) repo for content.  In the current beta, they have search, albeit only for payloads you've added (so this could be enhanced further).

Since you're discussing Chrome, if you were interested in helping with test cases, I have a PR in ProfileManifests for a reorganization of Chrome so keys are organized, rather than just being in a long list, to help address the fact that you can't search for things.

**Closed** 2019-11-01 15:39 UTC
Labels: duplicate
